
spring:
  application:
    name: yupao-backend
    #指定默认环境为dev
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # DataSource Config
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
    #    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/friend
#    username: root
#    password: 2017083122xuao
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.41.119:3306/user_center?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dog
    password: 123456

  # session 失效时间
  session:
    timeout: 86400
    #session存入redis
    store-type: redis

  redis:
    port: 6379
    host: 123.56.41.119
    password: 123456
    database: 0
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: 127.0.0.1
mybatis-plus:
  type-aliases-package: com.yupi.usercenter.model.domain
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印查询日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.knife4j.demo.new3